[env:esp32dev]
platform       = espressif32
board          = esp32dev
framework      = arduino
monitor_speed  = 115200
upload_speed   = 921600

build_flags =
    -Os                       ; optimise for size
    -DCORE_DEBUG_LEVEL=0      ; suppress SDK log output

board_build.filesystem = littlefs

lib_deps =
    mathieucarbou/ESPAsyncWebServer @ ^3.3.1
    bblanchon/ArduinoJson @ ^7.0.4
